name: wik
description: "WIK - Work In Korea"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.25.2
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.0
  firebase_ui_auth: ^1.12.1
  firebase_ui_firestore: ^1.6.1
  firebase_ui_localizations: ^1.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
